version: '3.8'

services:
  saas_frontend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_frontend_app
    restart: unless-stopped
    # Conectamos este contenedor a una red unificada para que Caddy pueda 'verlo' por su nombre
    networks:
      - saas_network

# Definimos que la red ya existe (será creada por el backend)
networks:
  saas_network:
    external: true
