server {
    listen 80;
    server_name localhost;
    
    # Raíz donde se sirve la app Angular compilada
    root /usr/share/nginx/html;
    index index.html;

    # Habilitar compresión GZIP para cargar súper rápido
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Si el usuario navega a .com/dashboard o pulsa F5
        # Trata de servir el archivo. Si no existe, sirve el index.html (Vital para Single Page Apps)
        try_files $uri $uri/ /index.html;
    }

    # Configuraciones extra para evitar problemas con Caddy como proxy inverso
    # y evitar bloquear estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
